data:
  seed: 777
  task: semantic_segmantation_nlsc
  areas: [
    1,2,3,4,5,6,7,8,9
  ]

model:
  arch: Unet
  encoder: mit_b0 #timm-efficientnet-b5

optim:
  lr: 1.e-4
  optimizer:  AdamW
  weight_decay: 1.e-5

training:
  batch_size: 64
  ckpt_path: null
  early_stop: no
  n_splits: 5
  epochs: 50
  gradient_clipping: 5
  val_interval: 1
  num_workers: 32
