data:
  seed: 777
  task: semantic_segmantation_nlsc

model:
  arch: Unet
  encoder: mit_b5
  # encoder: timm-efficientnet-b0

optim:
  lr: 5.e-5
  optimizer:  AdamW
  weight_decay: 1.e-5

training:
  batch_size: 64
  ckpt_path: null
  early_stop: no
  n_splits: 5
  epochs: 50
  gradient_clipping: 5
  val_interval: 1
  num_workers: 32
